/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author David Pérez Arias
 */
public class FramePrincipal extends javax.swing.JFrame {

    FrameFrases frameFrases;
    FrameEstadisticas frameEstadisticas;
    FrameJugadores frameJugadores;
    FrameJuego frameJuego;

    FrameAgregarJugadoresJuego frameAgregarJugadores;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();

        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        buttonGoJugar = new javax.swing.JButton();
        buttonGoJugadores = new javax.swing.JButton();
        buttonEstadis = new javax.swing.JButton();
        buttonGoFrases = new javax.swing.JButton();
        buttonConfig = new javax.swing.JButton();
        buttosSalir = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú principal");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setOpaque(true);

        buttonGoJugar.setBackground(new java.awt.Color(102, 255, 102));
        buttonGoJugar.setText("Jugar");
        buttonGoJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoJugarActionPerformed(evt);
            }
        });

        buttonGoJugadores.setBackground(new java.awt.Color(102, 255, 102));
        buttonGoJugadores.setText("Admin Jugadores");
        buttonGoJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoJugadoresActionPerformed(evt);
            }
        });

        buttonEstadis.setBackground(new java.awt.Color(255, 204, 153));
        buttonEstadis.setText("Estadisticas");
        buttonEstadis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEstadisActionPerformed(evt);
            }
        });

        buttonGoFrases.setBackground(new java.awt.Color(51, 153, 255));
        buttonGoFrases.setForeground(new java.awt.Color(255, 255, 255));
        buttonGoFrases.setText("Admin frases");
        buttonGoFrases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoFrasesActionPerformed(evt);
            }
        });

        buttonConfig.setBackground(new java.awt.Color(51, 153, 255));
        buttonConfig.setForeground(new java.awt.Color(255, 255, 255));
        buttonConfig.setText("Configuración");
        buttonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfigActionPerformed(evt);
            }
        });

        buttosSalir.setBackground(new java.awt.Color(204, 204, 204));
        buttosSalir.setText("Salir");
        buttosSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttosSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonGoJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEstadis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGoJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonGoFrases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(buttosSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonGoFrases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGoJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEstadis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttosSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGoJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoJugarActionPerformed

        try {

            Object[] numJugadores = {"1 Jugador", "2 Jugadores"};

            Object opcion = JOptionPane.showInputDialog(null, "",
                    "Selecciona la cantidad de jugadores",
                    JOptionPane.QUESTION_MESSAGE, null, numJugadores, numJugadores[0]);

            int numeroJugadores = Integer.parseInt(opcion.toString().charAt(0) + "");

            this.setVisible(false);

            if (this.frameAgregarJugadores == null) {
                this.frameAgregarJugadores = new FrameAgregarJugadoresJuego(numeroJugadores, this);
                //  this.frameJuego.setFramePrincipal(this);
            } else {
                this.frameAgregarJugadores.actualizarJugadores(numeroJugadores);
            }
            this.frameAgregarJugadores.setVisible(true);


        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_buttonGoJugarActionPerformed

    private void buttosSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttosSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttosSalirActionPerformed

    private void buttonGoFrasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoFrasesActionPerformed

        this.setVisible(false);

        if (this.frameFrases == null) {
            this.frameFrases = new FrameFrases();
            this.frameFrases.setFramePrincipal(this);
        } else {
            this.frameFrases.consultarFrases();
        }

        this.frameFrases.setVisible(true);

    }//GEN-LAST:event_buttonGoFrasesActionPerformed

    private void buttonGoJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoJugadoresActionPerformed

//        JOptionPane.showMessageDialog(this, "Función en desarrollo");
        this.setVisible(false);

        if (this.frameJugadores == null) {
            this.frameJugadores = new FrameJugadores();
            this.frameJugadores.setFramePrincipal(this);
        } else {
            this.frameJugadores.consultarJugadores();
        }

        this.frameJugadores.setVisible(true);
    }//GEN-LAST:event_buttonGoJugadoresActionPerformed

    private void buttonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfigActionPerformed

        JOptionPane.showMessageDialog(this, "Función en desarrollo");

    }//GEN-LAST:event_buttonConfigActionPerformed

    private void buttonEstadisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEstadisActionPerformed

//        JOptionPane.showMessageDialog(this, "Función en desarrollo");
        this.setVisible(false);

        if (this.frameEstadisticas == null) {
            this.frameEstadisticas = new FrameEstadisticas();
            this.frameEstadisticas.setFramePrincipal(this);
        } else {
            this.frameEstadisticas.consultarEstadisticas();
        }

        this.frameEstadisticas.setVisible(true);


    }//GEN-LAST:event_buttonEstadisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfig;
    private javax.swing.JButton buttonEstadis;
    private javax.swing.JButton buttonGoFrases;
    private javax.swing.JButton buttonGoJugadores;
    private javax.swing.JButton buttonGoJugar;
    private javax.swing.JButton buttosSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
